services:
  dicebear:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    tmpfs:
      - '/run'
      - '/tmp'
